### ISSUE TITLE
cool guys, can you update this file to support 4.19, there are several error

### ISSUE THREAD

**Issue by qloach** [liamkf/Unreal_FASTBuild#24]
cool guys, can you update this file to support 4.19, there are several error
and thanks!

**Comment by Nampo** [comment]
I'll add some info.
On Windows platform, currently the plugin Engine\Plugins\Experimental\ProxyLODPlugin doesn't compile with FASTBuild.
The problem is that the cpp file generated by UE4 must be compiled with the OPENVDB_STATICLIB macro set, but that macro is defined in another generated file, Definitions.ProxyLODMeshReduction.h. The definition file is forced included with the compiler option /FI"..somepath../Definitions.ProxyLODMeshReduction.h", but it is actually NEVER preprocessed when compiling with FASTBuild.
Should the /FI files be included in the .CompilerInputFiles maybe ? I'm not expert about managing compilers so I don't know.

**Comment by liamkf** [comment]
Hi there! We haven't moved to a 4.19 build yet, I'm able to build locally with a github version of 4.19 and just pushed changes to get past the simple compile problems that popped up. If you're using the github source version and have problems with it let me know (if you're building with VS2015 be aware of this issue as well which requires some fixups: https://github.com/fastbuild/fastbuild/issues/256).

We have had another report of the ProxyLODPlugin not building correctly. I believe it's a problem to do with how the thirdparty libs for that plugin are built in P4 builds when distributed, but we won't be able to investigate further here until we move to a 4.19 perforce build.

In the meantime if you're not using that plugin you could try just removing it until things are fixed. The other report of this problem worked around it by adding a new `bBuildLocallyWithFASTBuild` flag which performs similarly to `bBuildLocallyWithSNDBS`, and then marking the ProxyLODPlugin, DirectXMesh, OpenVDB, and UVAtlas modules as true with that flag, which also seems like a very reasonable workaround.

**Comment by Nampo** [comment]
Hi Liam, thanks for your fast reply! I'm using VS2015 and already did all the required fixes in the engine 4.19 and FastBuild.cs.

Would it be possible to have a look at the bBuildLocallyWithFASTBuild workaround for the ProxyLODPlugin ? I can't find anything about that, and I don't know where to start to implement it. I can add the flag to the ModuleRules, then how do I handle it ?
Also, it seems to be a convenient feature to have, you might want to add it officially maybe ...

**Comment by qloach** [comment]
hi Liam, thanks again for the push pop problem.

**Comment by liamkf** [comment]
Hi Marco!

It was only described to me, so I don't have it available either I'm afraid! 

I would have a look at the SNDBS.cs file though to see how it's handled to do something similar. I think you would add the flag to the modules as you mentioned, and then in FASTBuild.cs if that flag is set, run them through the local executor instead of adding it to the bff file.

**Comment by Nampo** [comment]
I'll leave here my solution, just in case.
I've looked into SNDBS.cs but I found the related code to be complex (it deals with threads, processes, prerequisites, etc) and I didn't want to duplicate all that code into FASTBuild.cs, so I just used an instance of the built in LocalExecutor for the problematic modules. Here is how my mod looks like (last part of ExecuteActions() function in FASTBuild.cs:

`

			bool FASTBuildResult = true;

			List<Action> ExecutableActions = new List<Action>();
			List<Action> LocalActions = new List<Action>();

			foreach (Action a in Actions)
			{
				if (CanExecuteRemotely(a))
				{
					ExecutableActions.Add(a);
				}
				else
				{
					LocalActions.Add(a);
				}
			}

			if (ExecutableActions.Count > 0)
			{
				Console.WriteLine("Executing " + ExecutableActions.Count + " Actions");

				string FASTBuildFilePath = Path.Combine(UnrealBuildTool.EngineDirectory.FullName, "Intermediate", "fbuild.bff");

				FASTBuildResult = CreateBffFile(ExecutableActions, FASTBuildFilePath);

				if (FASTBuildResult)
				{
					FASTBuildResult = ExecuteBffFile(FASTBuildFilePath);
				}
			}

			if (LocalActions.Count > 0)
			{
				Console.WriteLine("Executing LOCAL Actions (excluded from FASTBuild):");
				foreach (Action a in LocalActions) { ConsoleWriteActionShort(a); }

				ActionExecutor localExecutor = new LocalExecutor();

				FASTBuildResult = FASTBuildResult && localExecutor.ExecuteActions(LocalActions, bLogDetailedActionStats);
			}

			return FASTBuildResult;
`

I defined a function `bool CanExecuteRemotely(Action action)` to identify actions to execute locally.
In my version I check `Action.StatusDescription` (that usually contains the module name) against a list of tokens. Since I already implemented a .ini file support for configuring FASTBuild.cs, I just added a field to that ini file for my list of tokens, that currently just contains "ProxyLODMeshReduction". In that way, I could avoid an additional Unreal Engine mod, required to add the field bBuildLocallyWithFASTBuild to the ModuleRules (keeping the engine mods to a minimum is a good thing, trust me on that).

If someone is looking for ideas to work with, this may be of some help (I hope).

EDIT: I was wrong about including `Action.bCanExecuteRemotely` to my test, as most actions compiling PCH are marked false, but should be compiled by FASTBuild anyway.
Also, 
WARNING: this solution is NOT general, combining the results of the Local Executor and FASTBuild Executor for a proper linking requires some more work. I'll start by trying to run the LocalExecutor first and for Compile actions only, than see if FASTBuild can link the results.
EDIT2: it worked. FASTBuild can link stuff compiled by LocalExecutor (tested PC and XBoxOne, I was never able to make PS4 work even before ...).

**Comment by yass007** [comment]
Hi @Nampo , Thanks for your suggestions.
In order to minimize the amount of changes we have to do in the engine and use the built-in FB "AllowDistribution" flag, I have a pushed a small change that forces Module.ProxyLODMeshReduction to compile locally which fixes the linking problem for now.

It would be nice to dig deeper into the problem and understand why compiling locally vs remotely produces a different output and causes or not linking issues (missing symbols).

Cheers.

**Comment by yass007** [comment]
Fixed

**Comment by TheRealJokerMan** [comment]
@yass007 what is the actual fix? (I'm suffering the same problem).

**Comment by thethrasher666** [comment]
With the latest FASTBuild and running Unreal 4.19.2, Module.ProxyLODMeshReduction fails to link as above if caching is enabled.
